config/routes.rb
Rails.application.routes.draw do
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/movies', to: 'movies#show'
  get '/start_parsing', to: 'movies#start_parsing'
  get '/manager-panel', to: 'movies#manager'
  post '/new-movies-to-user', to: 'movies#create'
  put '/user-update/:id', to: 'users#ban'
  put '/user-update/unban/:id', to: 'users#unban'
  get '/manager-users/', to: 'users#manager_users'
  get '/manager-movies/', to: 'movies#manager_movies'

  get 'sessions/new'

  get 'users/new'

  root 'movies#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :movies
  resources :contact_forms

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource
  include ApplicationHelper


  def home
    @movies = Movie.all.order('created_at DESC').page(params[:page]).per(20)
    @movies_genre = Movie.all.select(:genre).uniq.order('genre ASC')
    @date_relist = Movie.all.select(:date_relist).uniq.order('date_relist DESC')
    @rating = (Movie.all.select(:rating).uniq).order('rating DESC')
    if params[:search]
      search
    end
  end




  def show
    @movies = current_user.movies.order('created_at DESC').page(params[:page]).per(20)
    if current_user.present? && current_user.role != 'ban'
      get_manager_page
    else
      flash[:danger] = "Sorry you are not registered or was banned"
      redirect_to root_path
    end

  end


  def create
    @movie = Movie.find(params[:Movies])
    @user = User.find_by_id(params[:id])
    @movie_status = @user.movies.find_by_id(@movie.id)
    if @movie_status == nil
      flash[:success] = "Movie '#{@movie.title.upcase}' to '#{@user.email.upcase}' Added"
      @user.movies << @movie
    else
      flash[:danger] = "This is Movie (#{@movie.title.upcase}) has already been added to this user (#{@user.email.upcase})"
    end
   redirect_to manager_panel_path
  end

  def destroy
    movie = Movie.find(params[:id]).destroy
    flash[:success] = "Movie #{movie.title} was DELETED"
    get_manager_page
    render action: 'manager'
  end



  def update
    @user_movies_list = Movie.find(params[:id])
    if @user_movies_list.update_attributes(params.require(:movie).permit(:title, :img, :genre, :date_relist,
                                                                         :ebay_link, :runtime, :rating, :desc, :movie_path, :trailer))
      flash[:success] = "Profile updated"
    else
      flash[:danger] = "Profile not updated"
    end
  end

  def manager
   @tab = 'movie'
   get_manager_page
  end

  def start_parsing
    ContentPopcorn.perform_async
  end

  private

  def search
    @movies = Movie.search(params[:search]).order('updated_at DESC').page(params[:page]).per(20)
    @movies = @movies.genre(params[:genre]).order('updated_at DESC').page(params[:page]).per(20)
    @movies = @movies.date_relist(params[:date_relist]).order('updated_at DESC').page(params[:page]).per(20)
    @movies = @movies.rating(params[:rating]).order('updated_at DESC').page(params[:page]).per(20)
  end

  def get_manager_page
    manager_page
    if params[:search]
      search
      @user_movies_list = @movies
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_manager_movies.html.erb
<div id="movies"><p class="tbus">Service control movies </p>
  <div class="container">
    <div class="row"><%= form_for manager_panel_path, method: :get, id: "movies_search" do %>
          <div class="col-md-5" style="padding-top: 8px">
            <div class="input-group">
              <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for..." %>
              <span class="input-group-btn">
                  <%= button_tag "Search", class: "btn btn-default" %>
                </span>
            </div>
          </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <div class="well" style="height: 100%">
          <table class="table">
            <thead class="thead-inverse">
            <tr>
              <th></th>
              <th>Name</th>
              <th>Release Date</th>
              <th>Running Time</th>
              <th>Rating</th>
              <th>Movie path</th>
              <th>Trailer path</th>
              <th>Ebay link</th>
              <th>Delete</th>

            </tr>
            </thead>

            <tbody>
            <tr>
              <% @user_movies_list.each do |m| %>
                  <td><%= image_tag(m.img, size: '150x200') %></td>
                  <td style="max-width: 200px"><%= best_in_place m, :title, as: :input %></td>
                  <td><%= best_in_place m, :date_relist, as: :input %></td>
                  <td style="overflow: hidden;max-width: 30px"><%= best_in_place m, :runtime, as: :input %></td>
                  <td style="overflow: hidden;max-width: 30px"><%= best_in_place m, :rating, as: :input %></td>
                  <td style="overflow: hidden;max-width: 150px"><%= best_in_place m, :movie_path, as: :input %></td>
                  <td style="overflow: hidden;max-width: 150px"><%= best_in_place m, raw(:trailer), as: :input %></td>
                  <td style="overflow: hidden;width: 150px;display: block;">
                    <%= best_in_place m, raw(:ebay_link), as: :input %></td>
                  <td><%= link_to('X', {controller: "movies", action: "destroy", id: m.id}, method: :delete, remote: true, class: "btn btn-xs knop btn-danger", data: {confirm: 'Are you sure?'}) %>
                  </td>
                  </tr>
                  </tbody>
              <% end %>
              </table>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/_manager_users.html.erb
<div id="manage_user">
  <div style="height: 800px" class="well">
    <div class="col-md-12  col-sm-12">
      <div style="padding: 10px"><%= link_to('Add new user', '#3', :class => "btn  add_usr btn-success") %> </div>
      <p class="tbus">Service control users </p>
      <table align="center" class="table  table-striped ">
        <thead>
        <tr class="success">
          <th style="text-align: center">id</th>
          <th style="text-align: center">Name</th>
          <th style="text-align: center">Email</th>
          <th style="text-align: center">Role</th>
          <th style="text-align: center">Data created account</th>
          <th style="text-align: center">Movies</th>
          <th style="text-align: center">Action</th>
          <th style="text-align: center"> Servise</th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |u| %>
            <tr>
              <td style="text-align: center"><%= u.id %></td>
              <td style="text-align: center"><%= u.name %></td>
              <td style="text-align: center"><%= u.email %></td>
              <td style="text-align: center"><%= u.role %></td>
              <td style="text-align: center"><%= u.created_at.strftime("%F") %></td>
              <td style="text-align: center"><%= u.movies.count %></td>
              <td>
                <%= button_tag('Watch list',
                               class: "btn btn-xs knop  btn-info", data: {toggle: 'modal', target: ".bs-example-modal-lg-#{u.id}"}) %>
                <div class="modal fade bs-example-modal-lg-<%= u.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="row">

                        <div class="col-md-12 col-sm-10">
                          <div style="height: 92%" class="well">
                            <table class="table">
                              <thead class="thead-inverse">
                              <tr>
                                <th></th>
                                <th>Name</th>
                                <th>Genre</th>
                                <th>Release Date</th>
                                <th>Running Time</th>
                                <th>Rating</th>
                                <th>Watched status</th>
                              </tr>
                              </thead>

                              <tbody>
                              <tr>
                                <% u.movies.each do |m| %>
                                    <td><%= image_tag(m.img, size: '150x200') %></td>
                                    <td><%= m.title %></td>
                                    <td><%= m.genre %></td>
                                    <td><%= m.date_relist %></td>
                                    <td><%= m.runtime %></td>
                                    <td><%= m.rating %></td>
                                    <td>status</td>
                                    </tr>
                                    </tbody>
                                <% end %>
                                </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>


                <button class="btn btn-xs knop btn-primary" type="button" data-toggle="collapse" data-target="#collapse-<%= u.id %>" aria-expanded="false" aria-controls="collapse-<%= u.id %>">
                  Add Movie
                </button>
                <div class="collapse" id="collapse-<%= u.id %>">
                  <div class="card card-block">
                    <%= form_tag(new_movies_to_user_path, action: 'create', method: :post) do %>
                        <%= select_tag "Movies", options_from_collection_for_select(@movies_list, "id", "title") %>
                        <input type="hidden" id="id" name="id" value="<%= u.id %>">
                        <%= submit_tag("Add movie to User #{u.email}") %>
                    <% end %>
                  </div>
                </div>
              </td>
              <td>
                <% if u.role == 'ban' %>
                    <%= link_to('Unban user', {controller: "users", action: "unban", id: u.id}, method: :put,
                                class: "btn btn-xs knop btn-danger active", data: {confirm: "Are you sure want Unban this user", toggle: 'button'}) %>
                <% else %>
                    <%= link_to('Ban user', {controller: "users", action: "ban", id: u.id}, method: :put,
                                class: "btn btn-xs knop btn-warning", data: {confirm: "Are you sure want Ban this user"}) %>
                <% end %>
                <%= link_to('Remove', {controller: "users", action: "destroy", id: u.id}, method: :delete, class: "btn btn-xs knop btn-danger", data: {confirm: 'Are you sure?'}) %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

    </div>




    <%= paginate @users, :theme => 'twitter-bootstrap-3', remote: true %>

  </div>
</div>

app/views/movies/_movies.html.erb
  <% @movies.each do |m| %>

      <div class="card">
        <div class="card__container card__container--closed">
          <svg class="card__image" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1920 1200" preserveAspectRatio="xMidYMid slice">
            <defs>
              <clipPath id="clipPath<%=m.id%>">
                <polygon class="clip" points="0,1200 0,0 1920,0 1920,1200"></polygon>
              </clipPath>
            </defs>
            <image clip-path="url(#clipPath<%=m.id%>)" width="1920" height="1200" xlink:href="<%= m.img %>"></image>
          </svg>
          <div class="card__content">
            <i class="card__btn-close fa fa-times"></i>
            <div class="card__caption">
              <h2 class="card__title"><%= m.title %></h2>
              <p class="card__subtitle">Genre - <%= m.genre.split(', ').join(', ').gsub(/\W/, ' ').strip.upcase %></p>
            </div>
            <div class="card__copy">
              <div class="meta">
                <img class="meta__avatar" src="<%= m.img %>" alt="author01" />
                <img class="krug"/>
                <div class="description">
                  <span class="meta__author">Running Time - <%= m.runtime %></span><br>
                  <span class="meta__date">Release Date - <%= m.date_relist %></span>
                </div>
              </div>
              <div class="text" style="text-align: center">
                <p>
                  <%= raw(m.trailer) %>
                  <%= link_to(image_tag('img/Buy-from-ebay.png'), raw(m.ebay_link)) if m.ebay_link.present? %>
                  <br>
                  <br>
                  <%= m.desc %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

    <% end %>

app/views/movies/home.html.erb
<div class="container">
  <h1>Movies</h1>
  <div class="content">
    <div class="wrapper">
      <div id="movies"> <%= render partial: 'movies' %></div>
    </div>
    <div style="margin: auto; display: table;"><%= paginate @movies, :theme => 'twitter-bootstrap-3'  %></div>
  </div>
</div>

app/views/movies/home.js.erb
$("#movies, .pagination").html("<%= escape_javascript(render("movies")) %>")

app/views/movies/manager.html.erb
<h1>Manager Panel</h1>
  <div class="container" align="center">

<div id="exTab2" class="container">
  <ul class="nav nav-tabs">
    <li class="active">
      <a  href="#1" data-toggle="tab">Users Control Tab</a>
    </li>
    <li><a href="#2" data-toggle="tab">Movies Control Tab</a>
    </li>
    <li><a href="#3" data-toggle="tab">User Form</a>
    </li>
    <li><a href="#4" data-toggle="tab">Start Parsing</a>
    </li>
  </ul>

  <div class="tab-content ">
    <div class="tab-pane <%= @tab == 'user' ? '' : 'active' %>" id="1">
      <%= render partial: "movies/manager_users", remote: true  %>
    </div>
    <div class="tab-pane <%= @tab == 'movie' ? 'active' : '' %>"  id="2">
      <%= render partial: "movies/manager_movies", remote: true  %>
      <div align="center" style="padding-bottom: 30px;">
        <%= paginate @user_movies_list, :theme => 'twitter-bootstrap-3' %>
      </div>
    </div>
    <div class="tab-pane" id="3">
      <%= render partial: "users/form", remote: true %>
    </div>
    <div class="tab-pane" id="4">
     <%= link_to 'Start parsing Ccontent',  start_parsing_path %>
    </div>
  </div>
</div>
</div>

app/views/movies/manager.js.erb
$("#well").html("<%= escape_javascript(render("users/form")) %>");
$("#movies").html("<%= escape_javascript(render("movies/manager_movies")) %>");
$("#manage_user").html("<%= escape_javascript(render("movies/manager_users")) %>");

app/views/movies/show.html.erb
<h1>Your Movies</h1>

<div class="container" , style="margin-bottom: 40px;">
  <% @movies.each do |m| %>
      <div class="container-fluid col-sm-4 col-md-3 ">
        <div class="well" style="width: 265px;" align="center">
          <p class="mouvi_title" align="center"><%= m.title %></p>
          <div class="cnt">
            <div class="gr_img">
              <%= image_tag(m.img, size: '200x300') %>
            </div>
            <br>
            <p class="genre">Genre : <%= m.genre.to_s.gsub(/"/, '').gsub(/\[/, '').gsub(/]/, '') %></p>

            <p class="genre" align="left">Rating : <%= m.rating %></p>
            <p class="genre" align="rigth">Runtime : <%= m.runtime %>  </p>
            <div class="buttons">
              <button type="button" style="margin-right: 8px;" class=" btn btn-success" data-toggle="modal" data-target=".bs-example-modal-lg-<%= m.id %>">View
                movie
              </button>
              <button type="button" class=" btn btn-success" data-toggle="modal" data-target=".bs-example-modal-lg-trailer-<%= m.id %>">View
                trailer
              </button>
            </div>
          </div>
        </div>

        <div class="modal  fade bs-example-modal-lg-trailer-<%= m.id %>" id="mod_w" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
          <div class="modal-dialog modal-lg " role="document">
            <div class="modal-content ">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel" align="center">
                  <%= m.title %>
                </h4>
                <div class="video_con" align="center" width="560"><%= raw(m.trailer) %></div>
              </div>
            </div>
          </div>
        </div>


        <div class="modal  fade bs-example-modal-lg-<%= m.id %>" id="mod_w" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
          <div class="modal-dialog modal-lg " role="document">
            <div class="modal-content ">
              <div class="modal-header">
                <h4 class="modal-title" id="gridSystemModalLabel" align="center">
                  <%= m.title %>
                </h4>
                <div class="video_con" align="center" width="560">
                  <% unless m.movie_path == nil %>
                      <%= render_video_for_vjs sources: { 'video/mp4': "#{m.movie_path}.mp4" },id: m.id, width:'700',
                                               height: '350', captions: { en: { 'English': "#{m.movie_path}.vtt" }} %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>



      </div>
  <% end %>
</div>

<div align="center" style="padding-bottom: 30px;"><%= paginate @movies, :theme => 'twitter-bootstrap-3' %></div>

app/views/movies/start_parsing.html.erb
<h1>Start Parsing</h1>