config/routes.rb
Rails.application.routes.draw do
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/movies', to: 'movies#show'
  get '/start_parsing', to: 'movies#start_parsing'
  get '/manager-panel', to: 'movies#manager'
  post '/new-movies-to-user', to: 'movies#create'
  put '/user-update/:id', to: 'users#ban'
  put '/user-update/unban/:id', to: 'users#unban'
  get '/manager-users/', to: 'users#manager_users'
  get '/manager-movies/', to: 'movies#manager_movies'

  get 'sessions/new'

  get 'users/new'

  root 'movies#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :movies
  resources :contact_forms

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom navbar-inverse" >
  <div align="center" style="height: 27px">
    All rights reserved  @ 2017
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "ebay-movies.club", root_path, id: "logo" %></li>
      </ul>
      <% if request.original_fullpath == '/' || request.original_fullpath.include?('search') %>
          <%= form_for root_path, method: :get, id: "movies_search" do %>
              <div class="col-md-5" style="padding-top: 8px">
                <div class="input-group">
                  <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for..." %>
                  <span class="input-group-btn">
                  <%= button_tag "Search", class: "btn btn-default" %>
                </span>
                </div>
              </div>
          <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
            <% if current_user.role == 'admin' %>
                <li><%= link_to "Manager Panel", manager_panel_path %></li>
            <% end %>
            <li><%= link_to "Your Movies", movies_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>

  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <%= render 'layouts/shim' %>

    <body class="demo-4">
        <%= render 'layouts/header' %>
        <!--------------svg фон страниц ----------------->
        <div class="pattern pattern--hidden"></div>
        <!----------------------------------------------->
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</head>
</body>
</html>